name: Deploy to Production

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types: [completed]

jobs:
  deploy:
    runs-on: self-hosted
    environment: production
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        shell: bash
        run: |
          "DATABASE_URL=${{ secrets.DATABASE_URL }}" | Out-File -FilePath .env -Encoding utf8
          "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" | Out-File -FilePath .env -Encoding utf8 -Append
          "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" | Out-File -FilePath .env -Encoding utf8 -Append

      - name: Deploy with Docker Compose
        shell: bash
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest
          docker compose down
          docker compose up -d
      
      - name: Notify Teams
        if: always()
        run: |
          curl -H "Content-Type: application/json" \
          -d "{
            \"@type\": \"MessageCard\",
            \"@context\": \"http://schema.org/extensions\",
            \"summary\": \"Deploy Status\",
            \"themeColor\": \"0076D7\",
            \"title\": \"Deploy Status local runner\",
            \"text\": \"Deploy completed with status: ${{ job.status }}\"
          }" \
          ${{ secrets.TEAMS_WEBHOOK_URL }}
